[package]
name = "opengl_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl33 = "0.2.1"
glutin = "0.28.0"
image = "0.24.2"
glm = "0.2.3"